return {
	ensure_installed = {
		"eslint-lsp",
		"biome",
		"prettierd",
		"tailwindcss-language-server",
		"typescript-language-server",
		"prismals",
		"gofumpt",
		"goimports",
		"golines",
		"gopls",
		"lua-language-server",
		"rust-analyzer",
		"rustfmt",
		"stylua",
		"omnisharp",
		"csharpier",
	},
}
